### ISSUE TITLE
BZOJ2242.cpp为空文件

### ISSUE THREAD

**Issue by Xeonacid** [lydrainbowcat/tedukuri#1]
[BZOJ2242.cpp](https://github.com/lydrainbowcat/tedukuri/blob/master/%E9%85%8D%E5%A5%97%E5%85%89%E7%9B%98/%E4%B9%A0%E9%A2%98/0x3B%20%E6%95%B0%E5%AD%A6%E7%9F%A5%E8%AF%86%20%E6%80%BB%E7%BB%93%E4%B8%8E%E7%BB%83%E4%B9%A0/%E8%AE%A1%E7%AE%97%E5%99%A8/BZOJ2242.cpp)

**Comment by lydrainbowcat** [comment]
fixed [41fe17e](https://github.com/lydrainbowcat/tedukuri/commit/41fe17e009864ddd1fd669246b9f16c99da4a1e0)
