### ISSUE TITLE
POJ1011 测试数据有误

### ISSUE THREAD

**Issue by kaloronahuang** [lydrainbowcat/tedukuri#11]
我的代码在 UVa 的评测中通过了，但是在本地测评时用 fc 发现结果不符。

**Comment by lydrainbowcat** [comment]
sticks.in中存在>50的数据（官方压缩包里的数据就是这样的……）
直接忽略掉超出范围的小木棍，即可得到sticks.out的结果，参阅POJ1011.cpp
不忽略的情况，可以以POJ1011_2.cpp的输出为准
