### ISSUE TITLE
第三版错误

### ISSUE THREAD

**Issue by Mintind** [lydrainbowcat/tedukuri#24]
版本：2018年11月第3次印刷

0x13 P58
链表中的initialize和insert函数不应该返回int
insert()也可以改为
`
int insert(int p, int val)
{
q = ++tot;
...
return q;
}
`

0x6A P437
最大流的Edmonds-Karp增广路算法中的图一，从D到B的边流量应该是6

**Comment by lydrainbowcat** [comment]
0x13 P58
Will change to `void`. Thanks.

0x6A P437
Has been fixed in 4th edition.
