### ISSUE TITLE
NOIP2011/CH2903 “Mayan游戏”标程有误

### ISSUE THREAD

**Issue by wuxigk** [lydrainbowcat/tedukuri#34]
```
2
1 0
1 0
2 2 0
1 0
2 0
```
输出结果应为
```
0 0 1
2 0 1
```

**Comment by lydrainbowcat** [comment]
已联系std编写者

**Comment by lydrainbowcat** [comment]
原std编写者不打算修改，已更换为yxc编写的std：https://github.com/lydrainbowcat/tedukuri/commit/64d7f98f0684d8c82031e63ac4100a6d12aa02d1
