### ISSUE TITLE
POJ2248 “Addition Chains”标程的问题

### ISSUE THREAD

**Issue by wuxigk** [lydrainbowcat/tedukuri#36]
@WFZWF 提供的标程默认最短Addition Chain满足性质X[k]=X[k-1]+X[i]其中1≤i≤k-1，但这个性质不总是正确的。首个反例是当n=12509时，最短Addition Chain长度为18(1 2 4 8 16 17 32 64 128 256 512 1024 1041 2082 4164 8328 12492 12509)，用标程中的算法将会得到长度为19的错误结果(1 2 4 8 16 32 64 128 256 512 1024 2048 4096 4160 4168 8336 12504 12508 12509).
尽管在本题的数据范围下此算法不会得到错误结果，且能够缩短运行时间，但是作为标程可能会对读者产生误导。

**Comment by lydrainbowcat** [comment]
Thanks for figuring out. Rolled back in https://github.com/lydrainbowcat/tedukuri/pull/40.
