### ISSUE TITLE
Contest Hunter 1813 数据是否有误？

### ISSUE THREAD

**Issue by yali-hzy** [lydrainbowcat/tedukuri#37]
第3个测试点第2组数据

对应数据输入：
6
2 6 3 1 5 4 
数据输出：
a c c a b b d a a b b d

实际上，有一个更小的字典序的方案
a c c a b b a a d b b d 

可能的原因：当S2栈顶元素可以弹出时，可以先不弹出，而先选择S1的入栈和出栈操作

没准是标程的问题

后面的数据应该也有类似问题

望及时修改

**Comment by lydrainbowcat** [comment]
这好像是个遗留问题，std也不是我写的。
已经修复：https://github.com/lydrainbowcat/tedukuri/commit/2b04d2af6fe8454e7f5f098f8079671eff72d20a
