### ISSUE TITLE
A minor bug in the definition of BST.

### ISSUE THREAD

**Issue by andylizf** [lydrainbowcat/tedukuri#39]
On page 233,
> 1. 该节点的关键码不小于它的右子树中任意节点的关键码
> 2. 该节点的关键码不大于他的右子树中任意节点的关键码

But in the following:
> 显然，二叉查找树的中序遍历时一个关键码单调递增的节点序列。

To avoid ambiguity, and meet the above definition, we should use `不严格单调递增` instead of `单调递增`, as `单调递增` means \forall x, y, f(x) < f(y).

**Comment by lydrainbowcat** [comment]
Will update in the next edition. Thanks!
