### ISSUE TITLE
BZOJ1999.pas无法通过样例和NOIP数据

### ISSUE THREAD

**Issue by Bubbleioa** [lydrainbowcat/tedukuri#4]
BZOJ上确实过了，但是NOIP的小数据居然过不了（而且样例也过不了，这样真的好吗）

**Comment by lydrainbowcat** [comment]
Fixed in [f2d5a56](https://github.com/lydrainbowcat/tedukuri/commit/f2d5a567ec9814890e2b6a02640c4e9a58fc074a).
