### ISSUE TITLE
有符号整数溢出是 UB

### ISSUE THREAD

**Issue by H-J-Granger** [lydrainbowcat/tedukuri#41]
在第 6 页里的代码片段：

> ```cpp
> long long mul(long long a, long long b, long long p) {
> 	a %= p, b %= p; // 当a,b一定在0~p之间时，此行不必要。
> 	long long c = (long double)a * b / p;
> 	long long ans = a * b - c * p;
> 	if (ans < 0) ans += p;
> 	else if (ans >= p) ans -= p;
> 	return ans;
> }
> ```

的 `a * b` 可能导致有符号整数溢出，这是 UB，在 C++20 的文档第 74 页 6.8.1 Fundamental types 第二条有说明。

**Comment by lydrainbowcat** [comment]
Thanks for figuring out.

Code fixed in https://github.com/lydrainbowcat/tedukuri/commit/1de9ed229f7d6f88fb9bd2547dcfc519c9630ebb.

Will fix in next edition:
![image](https://user-images.githubusercontent.com/3481723/82110760-b31cc480-977b-11ea-9b36-6f6e1c358b33.png)

**Comment by lydrainbowcat** [comment]
另外实际上编译器均按照与无符号相同的溢出实现，所以以前的代码用在竞赛中问题也不大。

**Comment by H-J-Granger** [comment]
倒是，但是作为一本教学用书籍来说最好还是不要出现ub

**Comment by lydrainbowcat** [comment]
Makes sense. 下一版将会更新为使用unsigned long long自然溢出计算。

**Comment by lydrainbowcat** [comment]
刚才的代码大的减小的好像不太对…… 又改了一下…… 最后的减法还是要用long long算

**Comment by xuke-hat** [comment]
返回值还是得long long吧。。

**Comment by xuke-hat** [comment]
> Thanks for figuring out.
> 
> Code [fixed](https://github.com/lydrainbowcat/tedukuri/blob/4cd4252658f3cf5cb38060be6d162070c235256d/%E9%85%8D%E5%A5%97%E5%85%89%E7%9B%98/%E4%BE%8B%E9%A2%98/0x00%20%E5%9F%BA%E6%9C%AC%E7%AE%97%E6%B3%95/0x01%20%E4%BD%8D%E8%BF%90%E7%AE%97/64%E4%BD%8D%E6%95%B4%E6%95%B0%E4%B9%98%E6%B3%95/CH0102%2064%E4%BD%8D%E6%95%B4%E6%95%B0%E4%B9%98%E6%B3%95%20%E6%96%B9%E6%B3%95%E4%BA%8C.cpp).
> 
> Will fix in next edition:
> ![image](https://user-images.githubusercontent.com/3481723/82111400-f6793200-977f-11ea-8f5f-17f51ebb2344.png)

返回值还是得long long吧。。
