### ISSUE TITLE
0x53 区间DP Polygon 

### ISSUE THREAD

**Issue by gandyli** [lydrainbowcat/tedukuri#43]
[这份代码](https://github.com/lydrainbowcat/tedukuri/blob/master/%E9%85%8D%E5%A5%97%E5%85%89%E7%9B%98/%E4%BE%8B%E9%A2%98/0x50%20%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92/0x53%20%E5%8C%BA%E9%97%B4DP/Polygon/POJ1179%20Polygon.cpp)开 O2 后会 RE，原因是把内置函数 `fmax`和`fmin` 作为数组名

**Comment by lydrainbowcat** [comment]
已在 https://github.com/lydrainbowcat/tedukuri/commit/331db2e0e4bb7d2ec21afc49a914f982c9b565f9 中更新。
该程序由热心群众编写，仅供思路参考。
