### ISSUE TITLE
0x01位运算例题起床困难综合症

### ISSUE THREAD

**Issue by yanyanlongxia** [lydrainbowcat/tedukuri#44]
主函数中的贪心策略应该有问题，在测试中只能拿70分
应将
`if(val+(1<<bit)<=m && res0<res1)
    val+=1<<bit,ans+=res1<<bit;
else
    ans+=res0<<bit;`
更改为
`if(res0==1)
            ans+=res0<<bit;
        else
        {
            if(val+(1<<bit)<=m&&res1==1)
                val+=1<<bit,ans+=res1<<bit;`

**Comment by lydrainbowcat** [comment]
在哪个测试只能拿70分？标程应该都测试通过了的。

**Comment by yanyanlongxia** [comment]
https://www.luogu.com.cn/record/34678670  这是我在洛谷上的提交记录

**Comment by yanyanlongxia** [comment]
这是我Hack到的一组数据，好像过不去。https://send.firefox.com/download/534cd73f2fb00b53/#Pe-14GIUmMFkuSKX2kopjA

**Comment by lydrainbowcat** [comment]
那是你自己写错了吧，标程在洛谷明明可以过的：https://www.luogu.com.cn/record/34707147

**Comment by yanyanlongxia** [comment]
> 那是你自己写错了吧，标程在洛谷明明可以过的：https://www.luogu.com.cn/record/34707147

谢谢，找到错了。
对不起打扰了
