### ISSUE TITLE
第128页排书的状态分支计算有误

### ISSUE THREAD

**Issue by upupming** [lydrainbowcat/tedukuri#50]
第六版书上第 128 页最下面写道：

<img src="https://latex.codecogs.com/gif.latex?s=\sum_{i%20=%20%201}^{n}%20(n-i)%20*%20(n-i+1)%20\le%20(15%20*%2014%20+%2014%20*%2013%20+%20\cdots%20+%202*1)%20/%202%20=%20560" />

这个地方有两个小问题（不过不影响理解）：

1. 不应该是 <=，而应该是 >=；我理解作者的意思是不是要表达状态数就是不超过前面那个表达式除以 2
2. 后面计算的结果应该是 561
![image](https://user-images.githubusercontent.com/24741764/103964211-e215f980-5195-11eb-822e-0680df0155f9.png)

作者书写的很好，感谢作者👍。

**Comment by lydrainbowcat** [comment]
`<=`号没有问题吧，状态数不超过561，所以就是<=561？

**Comment by lydrainbowcat** [comment]
560的问题下一版会修正

**Comment by lydrainbowcat** [comment]
![image](https://user-images.githubusercontent.com/3481723/104144666-82268980-5407-11eb-8b7c-14802e5a363d.png)
这个就是560吧…… 
你怎么算出561的……

**Comment by lydrainbowcat** [comment]
https://www.wolframalpha.com/input/?i=sigma+n*%28n-1%29%2F2+n%3D2..15

**Comment by upupming** [comment]
> `<=`号没有问题吧，状态数不超过561，所以就是<=561？

前面那一串式子没有除以 2，怎么会小于等于除以 2 之后的结果呢？

**Comment by upupming** [comment]
> https://www.wolframalpha.com/input/?i=sigma+n*%28n-1%29%2F2+n%3D2..15

ops，我算错了 😅 ，那这个没问题

**Comment by lydrainbowcat** [comment]
嗯，应该前面也/2
