### ISSUE TITLE
关于第六版322页 任务安排1 解法2的疑问

### ISSUE THREAD

**Issue by LeePenn** [lydrainbowcat/tedukuri#53]
其中F[i]:=把前i个任务分成若干批执行的最小费用，但是比如有三个任务，在计算F[1]时，其中包含了S*（sumC[3] - sumC[0]），那F[i]其实不应该是前1个任务分成若干批执行的最小费用，因为它包含了后续的费用，因此这个dp的定义是否有问题？

**Comment by lydrainbowcat** [comment]
严格来说 F[i] 把前i个任务分成若干批执行，对执行完全部任务所花费用的最小影响
简记为最小费用了

**Comment by LeePenn** [comment]
理解了，谢谢答复
