### ISSUE TITLE
第二章 基本数据结构 例题回文串的最大长度代码有误

### ISSUE THREAD

**Issue by LeePenn** [lydrainbowcat/tedukuri#55]
#include <cstdio>
#include <cstring>
#include <iostream>
#include <algorithm>
#define ull unsigned long long
using namespace std;
const int N = 1000006, P = 13331;
char s[N];
ull f1[N], f2[N], p[N];

ull H1(int i, int j) {
	return (f1[j] - f1[i - 1] * p[j - i + 1]);
}

ull H2(int i, int j) {
	return (f2[i] - f2[j + 1] * p[j - i + 1]);
}

int main() {
	int id = 0;
	p[0] = 1;
	for (int i = 1; i < N; i++) p[i] = p[i - 1] * P;
	while (scanf("%s", s + 1) && !(s[1] == 'E' && s[2] == 'N' && s[3] == 'D')) {
		++id;
		int ans = 0, len = strlen(s + 1);
		f2[len+1] = 0;
		for (int i = 1; i <= len; i++) f1[i] = f1[i - 1] * P + s[i];
		for (int i = len; i; i--) f2[i] = f2[i + 1] * P + s[i];
		for (int i = 1; i <= len; i++) {
                        // l初始化1有问题
                        // l需要从0开始，因为可能一开始l就小于r，类似这样的用例abcdefghijklmn，ans在i=1时会直接变成3
                        // int l = 1, r = min(i - 1, len - i);
			int l = 0, r = min(i - 1, len - i);
			while (l < r) {
				int mid = (l + r + 1) >> 1;
				if (H1(i - mid, i - 1) == H2(i + 1, i + mid)) l = mid;
				else r = mid - 1;
			}
			ans = max(l * 2 + 1, ans);
                        // l = 1, r = min(i - 1, len - i + 1);
			l = 0, r = min(i - 1, len - i + 1);
			while (l < r) {
				int mid = (l + r + 1) >> 1;
				if (H1(i - mid, i - 1) == H2(i, i + mid - 1)) l = mid;
				else r = mid - 1;
			}
			ans = max(l * 2, ans);
		}
		printf("Case %d: %d\n", id, ans);
	}
	return 0;
}

**Comment by lydrainbowcat** [comment]
啊这个程序不是我写的……
Fixed in https://github.com/lydrainbowcat/tedukuri/commit/3d49281c58a4135b7676aef75387c00a7aaefa59.

**Comment by LeePenn** [comment]
haha
