### ISSUE TITLE
ans 应该是从0开始吧

### ISSUE THREAD

**Issue by wherby** [lydrainbowcat/tedukuri#67]
https://github.com/lydrainbowcat/tedukuri/blob/aa649a6a244b95c82b8f0d886ffd0e94a80849ae/%E9%85%8D%E5%A5%97%E5%85%89%E7%9B%98/%E4%BE%8B%E9%A2%98/0x00%20%E5%9F%BA%E6%9C%AC%E7%AE%97%E6%B3%95/0x07%20%E8%B4%AA%E5%BF%83/Radar%20Installation/POJ1328%20Radar%20Installation.cpp#L36

**Comment by lydrainbowcat** [comment]
根据写法不同，01开始都有可能
