### ISSUE TITLE
疑问：关于 0x59 POJ3017 Cut the Sequence.cpp

### ISSUE THREAD

**Issue by leixy2004** [lydrainbowcat/tedukuri#69]
[POJ3017 Cut the Sequence.cpp](https://github.com/lydrainbowcat/tedukuri/blob/master/%E9%85%8D%E5%A5%97%E5%85%89%E7%9B%98/%E4%BE%8B%E9%A2%98/0x50%20%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92/0x59%20%E5%8D%95%E8%B0%83%E9%98%9F%E5%88%97%E4%BC%98%E5%8C%96DP/Cut%20the%20Sequence/POJ3017%20Cut%20the%20Sequence.cpp)
代码第 31 行的访问 `a[q[l+1]]` 是不是会导致超出队列范围啊？条件只满足了 `l<=r`。

**Comment by leixy2004** [comment]
经测试，加上`if (l < r)` 后仍然可以通过 acwing 的数据

**Comment by lydrainbowcat** [comment]
l <= r && q[l] <= c[i] 这两个条件应该不会同时满足，所以不会超出范围
