### ISSUE TITLE
疑问：关于 0x63 节的两次 BFS 求树的直径

### ISSUE THREAD

**Issue by hylwxqwq** [lydrainbowcat/tedukuri#70]
是否应当加上一句话？

> 在树上有负边权的时候不能使用两次BFS/DFS求树的直径。

感觉如果不加会误导一些没去自己证明的同学（

例题当中的 “巡逻” 一题就需要注意这一点，或许可以在这道题目下添加说明？

**Comment by lydrainbowcat** [comment]
这个在第7版（或者更早的版本？）已经更新过了：
值得注意的是，两次BFS求直径的方法只适用于边权均为非负的情况。如果树上存在负权边，那么刚才的证明就不再成立。根据第一次BFS选择的起点的不同，可能会找到不同的“端点 p”，进一步得到不同的直径，可能会得到错误解。读者可以尝试举出一个反例。此时只能使用树形DP算法来求树的直径。
