### ISSUE TITLE
0x12 队列 例题 蚯蚓 的单调性证明有误

### ISSUE THREAD

**Issue by dbxxx-oi** [lydrainbowcat/tedukuri#78]
$x_2$ 被切成的其中一个个数是 $x_2 - \lfloor p(x_2 + q)\rfloor$，书中写成了 $x_2 - \lfloor p(x_2 + q)\rfloor + q$；

其次单调性证明中

$x_1 - \lfloor px_1 \rfloor + q = \lfloor x_1 - px_1 \rfloor + q$ 是错的，应该是大于等于号。

 $\lfloor x_2 - p(x_2 +q) \rfloor +q = x_2 + q - \lfloor p(x_2 + q) \rfloor$ 也是错的，此处应该为小于等于号。

$\lfloor 1 - 0.3 \rfloor < 1 - \lfloor 0.3 \rfloor$。

**Comment by ACodinghusky** [comment]
不对，此处应该是小于等于号。$\lfloor 1 - 0.3 \rfloor < 1 - \lfloor 0.3 \rfloor$

**Comment by ACodinghusky** [comment]
给一个我自己写的正确性证明 https://www.luogu.com.cn/paste/c4jthmhz

**Comment by lydrainbowcat** [comment]
感谢指正并给出参考证明。

下一版将会修正：
![image](https://user-images.githubusercontent.com/3481723/220538889-ba029e70-8fa5-41f2-9f53-a2a3b3a326b5.png)
