### ISSUE TITLE
0x61 最短路 单源最短路径 Dijkstra算法时间复杂度有误

### ISSUE THREAD

**Issue by lingyunvoid** [lydrainbowcat/tedukuri#80]
原文：

> 上面程序的时间复杂度为 $O(n^2)$，主要瓶颈在于第 $1$ 步的寻找全局最小值的过程。可以用二叉堆（C++ STL priority_queue，0x71 节）对 $dist$ 数组进行维护，用 $O(\log n)$ 的时间获取最小值并从堆中删除，用 $O(\log n)$ 的时间执行一条边的扩展和更新，最终可在 $O(m\log n)$ 的时间内实现 Dijkstra 算法。
>
> ①: 严格来说，时间复杂度为 $O((m+n)\log n)$。为方便起见，我们假设 $m$ 的规模不小于 $n$ 的规模，因此简写为 $O(m\log n)$，下略。

参见 [**<font color=red>OI Wiki-最短路-Dijkstra 算法-时间复杂度</font>**](https://oi-wiki.org/graph/shortest-path/#时间复杂度)：

> 优先队列：和二叉堆类似，但使用优先队列时，如果同一个点的最短路被更新多次，因为先前更新时插入的元素不能被删除，也不能被修改，只能留在优先队列中，故优先队列内的元素个数是 $O(m)$ 的，时间复杂度为 $O(m \log m)$。

综上：严格来说，优先队列优化的 Dijkstra 时间复杂度为 $O((m+n)\log m)=O(m\log m)$。

若用二叉堆实现：

> 二叉堆：每成功松弛一条边 $(u,v)$，就将 $v$ 插入二叉堆中（如果 $v$ 已经在二叉堆中，直接修改相应元素的权值即可），1 操作直接取堆顶结点即可。共计 $O(m)$ 次二叉堆上的插入（修改）操作，$O(n)$ 次删除堆顶操作，而插入（修改）和删除的时间复杂度均为 $O(\log n)$，时间复杂度为 $O((n+m) \log n) = O(m \log n)$。

可以做到严格的 $O(m\log n)$。

**Comment by lydrainbowcat** [comment]
一般来说 m <= n^2
O(log m) <= O(log n^2) = O(2 log n) = O(log n)
故我们一般不区分 logm 和 logn 的差别。
