### ISSUE TITLE
大象出版社新版0x01节无《最短Hamilton路径》例题

### ISSUE THREAD

**Issue by gtn1024** [lydrainbowcat/tedukuri#81]
大象出版社新版0x01节无《最短Hamilton路径》例题。

![212321060-f3124af3-c521-4a93-be14-e9881434d673.jpg)](https://user-images.githubusercontent.com/69113276/212321060-f3124af3-c521-4a93-be14-e9881434d673.jpg)

![212321082-cad6be1e-27b3-43c2-a21c-af9268f21cd2.jpg](https://user-images.githubusercontent.com/69113276/212321082-cad6be1e-27b3-43c2-a21c-af9268f21cd2.jpg)

**Comment by tabbbbbb** [comment]
您好，您的邮件已收到，谢谢！

**Comment by lydrainbowcat** [comment]
这道题改到了状态压缩DP那一节。相关的描述将在下次印刷时更新，谢谢！
