### ISSUE TITLE
0x66 Tarjan算法 割边判定法则 语言表述修改建议

### ISSUE THREAD

**Issue by qpdk777** [lydrainbowcat/tedukuri#82]
在“割边判定法则”小节中，第一句话“无向边(x,y)是桥，当且仅当搜索树上存在x的一个子节点y，满足：dfn[x]<low[y]”表述令人难以理解。“x是y的父节点”作为题设的一个前提条件，应当放置在(x,y)这条边出现之前，或单独提出来作为强调。
建议改为： “无向边(x,y)是桥，当且仅当：1. 搜索树中，x是y的父节点；2. dfn[x]<low[y]”

**Comment by lydrainbowcat** [comment]
下一次印刷将改为：

割边判定法则
无向边 (x,y) 是桥，当且仅当搜索树上 x 是 y 的父节点，且满足：
dfn[x]<low[y]

感谢提出建议。
