### ISSUE TITLE
淘宝上出现盗版书

### ISSUE THREAD

**Issue by ZhangYaoan** [lydrainbowcat/tedukuri#88]
淘宝上出现盗版书，希望各位OIer不要上当受骗，也请作者注意 @lydrainbowcat 
盗版书（[商品链接](https://m.tb.cn/h.UzngBAn?tk=kRoxdrEjYym)）:
![IMG_20230620_214801.jpg](https://img1.imgtp.com/2023/06/20/YCoySvto.jpg)
![IMG_20230620_214805.jpg](https://img1.imgtp.com/2023/06/20/NXonxsJv.jpg)
![IMG_20230620_214816.jpg](https://img1.imgtp.com/2023/06/20/ePQCDlte.jpg)

**Comment by tabbbbbb** [comment]
您好，您的邮件已收到，谢谢！

**Comment by lydrainbowcat** [comment]
最新版换了出版社和排版，在这里：https://item.jd.com/10067239761146.html

淘宝举报并没有什么用……
