### ISSUE TITLE
有关「最短 Hamilton 路径」的问题

### ISSUE THREAD

**Issue by Mindigma** [lydrainbowcat/tedukuri#93]
书为 2022.11 第一版，2023.8 第二次印刷。

在旧版 0x01「二进制状态压缩」中有「最短 Hamilton 路径」，但在该版中找不到该题目，并且该版 0x02 的「递推与递归的简单应用」中有提到「上一节中最短 Hamilton 路径问题的朴素做法，是一种……」（15 页）。

**Comment by tabbbbbb** [comment]
您好，您的邮件已收到，谢谢！

**Comment by XiongDiNanDang** [comment]
这题在 0x56 状态压缩类 DP 中作为第 1 道例题。

疑似更换题目没更新全，后面的表里也有好多题和书中的对不上。

还有，这书是停止维护了么，已经积压了好多 issues 了……

**Comment by XiongDiNanDang** [comment]
这个问题在#81 里提了，建议 close 掉。
